default_language_version:
  node: 17.9.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      # - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [-l 90]
        additional_dependencies: ["click==8.0.4"] # TODO: Remove this line when upgrading black to 22.3.0+.

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black, -l, "90", --lines-after-imports, "2"]

  - repo: https://git.evocargo.com/thirdparty/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8 (py2)
        args: [--max-line-length=90, "--ignore=E203,E231,W503,E266,E999"]
        language_version: python2
      - id: flake8
        name: flake8 (py3)
        args: [--max-line-length=90, "--ignore=E203,E231,W503,E266,B301"]
        additional_dependencies: [flake8-bugbear]
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        args: [--print-width=80, --prose-wrap=always]

  - repo: local
    hooks:
      # - id: check-pre-commit-config-files
      #   name: check-pre-commit-config-files
      #   description: Check all required config files for pre-commit hook.
      #   entry: pre_commit_configs/check_pre_commit_config_files.sh
      #   language: system
      #   types: [file]
      - id: clang-format
        name: clang-format
        description: Formats C, C++, Objective-C, and Java code
        entry: clang-format
        args: [-i]
        language: python
        types: [c++]
      - id: cmake-lint
        name: cmake-lint
        description:
          cmake-lint will check your listfiles for style violations, common
          mistakes, and anti-patterns.
        entry: cmake-lint
        language: python
        types: [cmake]
      - id: cmake-format
        name: cmake-format
        description:
          cmake-format can format your listfiles nicely so that they don't look
          like crap.
        entry: cmake-format -c cmake_format.yaml
        args: [-i]
        language: python
        types: [cmake]
