version: "3"
services:
  dev_container:
    container_name: dev_container
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - ../..:/data
      - ..:/workspace/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility,graphics
      - NVIDIA_VISIBLE_DEVICES=all

  # dev_container_gpu:
  #   container_name: dev_container
  #   extends:
  #     service: dev_container
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]
