name: CI pipeline
on: push
jobs:
  lint:
    runs-on: ununtu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: pre-commit check
      - name: build
        run: echo build code
