name: workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get -y install \
            python3-pip clang-format \
            build-essential gdb cmake cppcheck
          pip3 install pre-commit cmakelang
      - name: lint
        run: pre-commit run --all-files
  test:
    needs: [lint]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON \
          -DENABLE_COVERAGE=OFF \
          -DENABLE_SANITIZER_ADDRESS=OFF -DENABLE_SANITIZER_LEAK=OFF \
          -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=OFF ..
          cmake --build . --target all -- -j8
          ctest --output-or-failure --verbose
  deploy:
    needs: [test]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build artifacts
        run: |
          mkdir build && cd build
          cmake -DBUILD_TYPE=Release ..  && cmake --build .
          cpack
      - name: Upload static artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static_artifacts
          path: build/*.deb
  coverage:
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt-get -y install lcov
      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON ..
          cmake --build . --target all -- -j8
      - name: Generate report
        run: |
          lcov -c -d . -o main_coverage.info
          genhtml main_coverage.info --output-directory out
